# Generated by Django 3.2.6 on 2021-10-19 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='total_interest',
        ),
    ]
